### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by Mo89f** [awang104-2/burgers-1d-godunov#4]
I need you help please in regard of the solution of burger equation. is it possible to have a x fom -1 to 1 . 
Thanks a lot

**Comment by awang104-2** [comment]
I updated the tester so the x coordinates reflect the chosen domain. The variable "domain" in the tester towards the end is the range of x over which you're finding/estimating the solution of the Burgers equation. Change that to whatever x you want (in your case, [-1,1]).

**Comment by Mo89f** [comment]
thanks alot have a nice day
